# Renders the Play listing graphics with headless Edge. Run from anywhere:
#
#   powershell -File store\render.ps1
#
# icon-512.png is built from app/src/main/res/drawable/ic_launcher_foreground.xml on every
# run, so the listing icon and the launcher icon cannot drift apart. The palette below is
# duplicated from ui/theme/Color.kt (there is no way to share constants across that
# boundary); if the theme changes, change it here too.

$ErrorActionPreference = "Stop"
$store = $PSScriptRoot
$root = Split-Path $store
$src = Join-Path $store "src"
New-Item -ItemType Directory -Force $src | Out-Null

$graphite = "#10151F"; $cellFill = "#1A2130"; $gridMinor = "#323D55"; $gridMajor = "#8C98B3"
$cage = "#8E9AB4"; $tangerine = "#FF9A4D"; $ink = "#F2F4F8"; $muted = "#B3BDD2"

# --- icon: the launcher vector's visible 72dp, full-bleed (Play applies its own mask) ------
$fg = [IO.File]::ReadAllText((Join-Path $root "app\src\main\res\drawable\ic_launcher_foreground.xml"))
$paths = [regex]::Matches($fg, '<path\s+([^>]*?)/>', 'Singleline') | ForEach-Object {
    $a = $_.Groups[1].Value
    $d = [regex]::Match($a, 'pathData="([^"]*)"').Groups[1].Value
    $fill = [regex]::Match($a, 'fillColor="([^"]*)"').Groups[1].Value
    $stroke = [regex]::Match($a, 'strokeColor="([^"]*)"').Groups[1].Value
    $w = [regex]::Match($a, 'strokeWidth="([^"]*)"').Groups[1].Value
    "<path d=""$d"" fill=""$(if ($fill) { $fill } else { 'none' })"" stroke=""$(if ($stroke) { $stroke } else { 'none' })"" stroke-width=""$w"" stroke-linecap=""round"" stroke-linejoin=""round""/>"
}
@"
<!doctype html>
<!-- Generated by store/render.ps1 from the launcher vector. Do not edit by hand. -->
<html><body style="margin:0;background:$graphite">
<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72" width="512" height="512" style="display:block">
<rect width="108" height="108" fill="$graphite"/>
$($paths -join "`n")
</svg></body></html>
"@ | Set-Content -Encoding utf8 (Join-Path $src "icon.html")

# --- feature graphic: one 3x3 box of a real-looking board -------------------------------
# Digits 8 1 6 / 3 5 7 / 4 9 2, cages A=8+3=11, B=1+6=7, C=5+4+9=18, D=7+2=9, so every
# sum shown is honest. Outlines use the app's own corner rules (game/CageOutlines.kt).
$layout = @(@('A','B','B'), @('A','C','D'), @('C','C','D'))
$sums = @{ A = 11; B = 7; C = 18; D = 9 }
$cellPx = 104; $ox = 620; $oy = (500 - 3 * 104) / 2; $inset = $cellPx * 0.09
function Same($r, $c, $dr, $dc) { $nr = $r + $dr; $nc = $c + $dc; return ($nr -ge 0 -and $nr -le 2 -and $nc -ge 0 -and $nc -le 2 -and $layout[$nr][$nc] -eq $layout[$r][$c]) }
function EndOf($r, $c, $pr, $pc, $sr, $sc) { if (-not (Same $r $c $pr $pc)) { 1 } elseif (Same $r $c ($pr + $sr) ($pc + $sc)) { -1 } else { 0 } }
$lines = New-Object System.Collections.Generic.List[string]
for ($r = 0; $r -lt 3; $r++) { for ($c = 0; $c -lt 3; $c++) {
    $x = $ox + $c * $cellPx; $y = $oy + $r * $cellPx
    $color = if ($layout[$r][$c] -eq 'C') { $tangerine } else { $cage }
    # Each coordinate in its own parentheses: PowerShell's comma binds tighter than '*'.
    $segs = @()
    if (-not (Same $r $c -1 0)) { $segs += , @(($x + (EndOf $r $c 0 -1 -1 0) * $inset), ($y + $inset), ($x + $cellPx - (EndOf $r $c 0 1 -1 0) * $inset), ($y + $inset)) }
    if (-not (Same $r $c 1 0)) { $segs += , @(($x + (EndOf $r $c 0 -1 1 0) * $inset), ($y + $cellPx - $inset), ($x + $cellPx - (EndOf $r $c 0 1 1 0) * $inset), ($y + $cellPx - $inset)) }
    if (-not (Same $r $c 0 -1)) { $segs += , @(($x + $inset), ($y + (EndOf $r $c -1 0 0 -1) * $inset), ($x + $inset), ($y + $cellPx - (EndOf $r $c 1 0 0 -1) * $inset)) }
    if (-not (Same $r $c 0 1)) { $segs += , @(($x + $cellPx - $inset), ($y + (EndOf $r $c -1 0 0 1) * $inset), ($x + $cellPx - $inset), ($y + $cellPx - (EndOf $r $c 1 0 0 1) * $inset)) }
    foreach ($s in $segs) { $lines.Add(("<line x1='{0:0.#}' y1='{1:0.#}' x2='{2:0.#}' y2='{3:0.#}' stroke='$color' stroke-width='3' stroke-dasharray='8 6'/>" -f $s[0], $s[1], $s[2], $s[3])) }
} }
$labels = foreach ($k in $sums.Keys) {
    $cells = for ($r = 0; $r -lt 3; $r++) { for ($c = 0; $c -lt 3; $c++) { if ($layout[$r][$c] -eq $k) { $r * 3 + $c } } }
    $a = ($cells | Measure-Object -Minimum).Minimum; $r = [math]::Floor($a / 3); $c = $a % 3
    $color = if ($k -eq 'C') { $tangerine } else { $ink }
    "<rect x='$($ox + $c * $cellPx + $inset * 0.5)' y='$($oy + $r * $cellPx + $inset * 0.5)' width='$(if ($sums[$k] -ge 10) {30} else {18})' height='24' fill='$cellFill'/><text x='$($ox + $c * $cellPx + $inset * 0.8)' y='$($oy + $r * $cellPx + $inset + 16)' fill='$color' font-size='20' font-weight='600' font-family='Fredoka, sans-serif'>$($sums[$k])</text>"
}
function Big($r, $c, $d) { "<text x='$($ox + $c * $cellPx + $cellPx / 2)' y='$($oy + $r * $cellPx + $cellPx / 2 + 22)' fill='$ink' font-size='58' font-weight='500' text-anchor='middle' font-family='Fredoka, sans-serif'>$d</text>" }
function Notes($r, $c, $text) { "<text x='$($ox + $c * $cellPx + $cellPx / 2)' y='$($oy + $r * $cellPx + $cellPx / 2 + 10)' fill='$muted' font-size='22' text-anchor='middle' font-family='Outfit, sans-serif' letter-spacing='8'>$text</text>" }
$box = $cellPx * 3
@"
<!doctype html>
<!-- Generated by store/render.ps1. Edit the script, not this file. -->
<html><head>
<link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@500;600&family=Outfit:wght@400;600&display=block" rel="stylesheet">
<style>
  body { margin:0; width:1024px; height:500px; background:$graphite; font-family:Outfit, sans-serif; overflow:hidden }
  .copy { position:absolute; left:72px; top:50%; transform:translateY(-50%); width:480px }
  h1 { font-family:Fredoka, sans-serif; font-weight:600; font-size:72px; line-height:1; margin:0; color:$ink }
  h1 span { color:$tangerine }
  p { font-size:28px; line-height:1.3; color:$muted; margin:22px 0 0 }
  .facts { font-size:20px; color:$muted; margin-top:34px; letter-spacing:.02em }
  .facts b { color:$ink; font-weight:600 }
</style></head><body>
<div class="copy">
  <h1>Killer <span>Sudoku</span></h1>
  <p>Every cage adds up.<br>No guessing, ever.</p>
  <div class="facts"><b>5,000</b> puzzles &middot; hints that explain &middot; offline</div>
</div>
<svg width="1024" height="500" style="position:absolute;left:0;top:0">
  <rect x="$ox" y="$oy" width="$box" height="$box" rx="10" fill="$cellFill"/>
  <line x1="$($ox + $cellPx)" y1="$oy" x2="$($ox + $cellPx)" y2="$($oy + $box)" stroke="$gridMinor" stroke-width="1.5"/>
  <line x1="$($ox + 2 * $cellPx)" y1="$oy" x2="$($ox + 2 * $cellPx)" y2="$($oy + $box)" stroke="$gridMinor" stroke-width="1.5"/>
  <line x1="$ox" y1="$($oy + $cellPx)" x2="$($ox + $box)" y2="$($oy + $cellPx)" stroke="$gridMinor" stroke-width="1.5"/>
  <line x1="$ox" y1="$($oy + 2 * $cellPx)" x2="$($ox + $box)" y2="$($oy + 2 * $cellPx)" stroke="$gridMinor" stroke-width="1.5"/>
  <rect x="$ox" y="$oy" width="$box" height="$box" rx="10" fill="none" stroke="$gridMajor" stroke-width="3"/>
  $($lines -join "`n  ")
  $($labels -join "`n  ")
  $(Big 0 0 8) $(Big 1 0 3) $(Big 1 1 5) $(Big 2 0 4)
  $(Notes 0 1 '1 6') $(Notes 0 2 '1 6') $(Notes 2 1 '9')
  <rect x="$($ox + 2 * $cellPx + 4)" y="$($oy + 2 * $cellPx + 4)" width="$($cellPx - 8)" height="$($cellPx - 8)" rx="12" fill="none" stroke="$tangerine" stroke-width="4"/>
</svg>
</body></html>
"@ | Set-Content -Encoding utf8 (Join-Path $src "feature.html")

# --- render ------------------------------------------------------------------------------
$edge = @("C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe", "C:\Program Files\Microsoft\Edge\Application\msedge.exe") | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $edge) { throw "Microsoft Edge not found; it is used as the headless renderer." }
function Render($html, $png, $w, $h) {
    # Edge reports "N bytes written" on stderr, which Windows PowerShell 5 turns into a
    # terminating error under "Stop". It is not an error; the file is checked below instead.
    $ErrorActionPreference = "Continue"
    $url = "file:///" + (Join-Path $src $html).Replace('\', '/')
    & $edge --headless=new --disable-gpu --hide-scrollbars --force-device-scale-factor=1 "--window-size=$w,$h" --virtual-time-budget=4000 "--screenshot=$(Join-Path $store $png)" $url 2>$null | Out-Null
    Start-Sleep -Milliseconds 800
    if (-not (Test-Path (Join-Path $store $png))) { throw "Edge did not write $png" }
    Write-Host "wrote store\$png"
}
Render "icon.html" "icon-512.png" 512 512
Render "feature.html" "feature-graphic-1024x500.png" 1024 500
